---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuwei.
--- DateTime: 2018/4/19 11:13
---

local find = string.find
local lower = string.lower

local _M = {}

local function is_json_body(content_type)
  return content_type and find(lower(content_type), "application/json", nil, true)
end

local function is_body_transform_set(conf)
  return #conf.replace.json > 0 and conf.replace.rate > 0
end

-- export utility functions
_M.is_json_body = is_json_body
_M.is_body_transform_set = is_body_transform_set

function _M.transform_headers(conf, ngx_headers)
  -- Removing the content-length header because the body is going to change
  if is_body_transform_set(conf) and is_json_body(ngx_headers["content-type"]) then
    ngx_headers["content-length"] = nil
  end
end

return _M
