---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuwei.
--- DateTime: 2018/4/9 18:48
---
---

local charset = {}

-- qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890
for i = 48,  57 do table.insert(charset, string.char(i)) end
for i = 65,  90 do table.insert(charset, string.char(i)) end
for i = 97, 122 do table.insert(charset, string.char(i)) end

local mt = getmetatable('')

local _M = {}

function _M.random(length)
  if not length or length <= 0 then return '' end

  math.randomseed(os.clock()^5)
  return _M.random(length - 1) .. charset[math.random(1, #charset)]
end

-- 是否为nil或空
function _M.isNilOrEmpty(str)
  return str == nil or str == ''
end

-- 返回由指定分隔符分割的数组
function _M.split(str, delimiter)
  if _M.isNilOrEmpty(str) or _M.isNilOrEmpty(delimiter) then
    return nil
  end

  local result = {}
  for match in (str..delimiter):gmatch("(.-)"..delimiter) do
    table.insert(result, match)
  end
  return result
end

return _M
